#pragma once

#include <array>

#include "nes/common.hpp"

namespace nes {

enum class OpType : byte_t {
  Adc,
  And,
  Asl,
  Bcc,
  Bcs,
  Beq,
  Bit,
  Bmi,
  Bne,
  Bpl,
  Brk,
  Bvc,
  Bvs,
  Clc,
  Cld,
  Cli,
  Clv,
  Cmp,
  Cpx,
  Cpy,
  Dec,
  Dex,
  Dey,
  Eor,
  Ill,
  Inc,
  Inx,
  Iny,
  Jmp,
  Jsr,
  Lda,
  Ldx,
  Ldy,
  Lsr,
  Nop,
  Ora,
  Pha,
  Php,
  Pla,
  Plp,
  Rol,
  Ror,
  Rti,
  Rts,
  Sbc,
  Sec,
  Sed,
  Sei,
  Sta,
  Stx,
  Sty,
  Tax,
  Tay,
  Tsx,
  Txa,
  Txs,
  Tya,
};

enum class OpMode : byte_t {
  Absolute,
  AbsoluteX,
  AbsoluteY,
  Immediate,
  Implied,
  Indirect,
  IndirectX,
  IndirectY,
  Relative,
  ZeroPage,
  ZeroPageX,
  ZeroPageY,
};

struct OpInfo {
  OpType type;
  OpMode mode;
  byte_t cycles;
  bool slow_on_page_cross;
  char const* name;
  addr_t address = 0;
};

// clang-format off
inline constexpr std::array optable = {
  OpInfo{OpType::Brk, OpMode::Implied  , 7, false, "brk"},
  OpInfo{OpType::Ora, OpMode::IndirectX, 6, false, "ora"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Nop, OpMode::ZeroPage , 3, false, "nop"},
  OpInfo{OpType::Ora, OpMode::ZeroPage , 3, false, "ora"},
  OpInfo{OpType::Asl, OpMode::ZeroPage , 5, false, "asl"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Php, OpMode::Implied  , 3, false, "php"},
  OpInfo{OpType::Ora, OpMode::Immediate, 2, false, "ora"},
  OpInfo{OpType::Asl, OpMode::Implied  , 2, false, "asl"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Nop, OpMode::Absolute , 4, false, "nop"},
  OpInfo{OpType::Ora, OpMode::Absolute , 4, false, "ora"},
  OpInfo{OpType::Asl, OpMode::Absolute , 6, false, "asl"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Bpl, OpMode::Relative , 2, true , "bpl"},
  OpInfo{OpType::Ora, OpMode::IndirectY, 5, true , "ora"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Nop, OpMode::ZeroPageX, 4, false, "nop"},
  OpInfo{OpType::Ora, OpMode::ZeroPageX, 4, false, "ora"},
  OpInfo{OpType::Asl, OpMode::ZeroPageX, 6, false, "asl"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Clc, OpMode::Implied  , 2, false, "clc"},
  OpInfo{OpType::Ora, OpMode::AbsoluteY, 4, true , "ora"},
  OpInfo{OpType::Nop, OpMode::Implied  , 2, false, "nop"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Nop, OpMode::AbsoluteX, 4, true , "nop"},
  OpInfo{OpType::Ora, OpMode::AbsoluteX, 4, true , "ora"},
  OpInfo{OpType::Asl, OpMode::AbsoluteX, 7, false, "asl"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Jsr, OpMode::Absolute , 6, false, "jsr"},
  OpInfo{OpType::And, OpMode::IndirectX, 6, false, "and"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Bit, OpMode::ZeroPage , 3, false, "bit"},
  OpInfo{OpType::And, OpMode::ZeroPage , 3, false, "and"},
  OpInfo{OpType::Rol, OpMode::ZeroPage , 5, false, "rol"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Plp, OpMode::Implied  , 4, false, "plp"},
  OpInfo{OpType::And, OpMode::Immediate, 2, false, "and"},
  OpInfo{OpType::Rol, OpMode::Implied  , 2, false, "rol"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Bit, OpMode::Absolute , 4, false, "bit"},
  OpInfo{OpType::And, OpMode::Absolute , 4, false, "and"},
  OpInfo{OpType::Rol, OpMode::Absolute , 6, false, "rol"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Bmi, OpMode::Relative , 2, true , "bmi"},
  OpInfo{OpType::And, OpMode::IndirectY, 5, true , "and"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Nop, OpMode::ZeroPageX, 4, false, "nop"},
  OpInfo{OpType::And, OpMode::ZeroPageX, 4, false, "and"},
  OpInfo{OpType::Rol, OpMode::ZeroPageX, 6, false, "rol"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Sec, OpMode::Implied  , 2, false, "sec"},
  OpInfo{OpType::And, OpMode::AbsoluteY, 4, true , "and"},
  OpInfo{OpType::Nop, OpMode::Implied  , 2, false, "nop"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Nop, OpMode::AbsoluteX, 4, true , "nop"},
  OpInfo{OpType::And, OpMode::AbsoluteX, 4, true , "and"},
  OpInfo{OpType::Rol, OpMode::AbsoluteX, 7, false, "rol"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Rti, OpMode::Implied  , 6, false, "rti"},
  OpInfo{OpType::Eor, OpMode::IndirectX, 6, false, "eor"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Nop, OpMode::ZeroPage , 3, false, "nop"},
  OpInfo{OpType::Eor, OpMode::ZeroPage , 3, false, "eor"},
  OpInfo{OpType::Lsr, OpMode::ZeroPage , 5, false, "lsr"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Pha, OpMode::Implied  , 3, false, "pha"},
  OpInfo{OpType::Eor, OpMode::Immediate, 2, false, "eor"},
  OpInfo{OpType::Lsr, OpMode::Implied  , 2, false, "lsr"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Jmp, OpMode::Absolute , 3, false, "jmp"},
  OpInfo{OpType::Eor, OpMode::Absolute , 4, false, "eor"},
  OpInfo{OpType::Lsr, OpMode::Absolute , 6, false, "lsr"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Bvc, OpMode::Relative , 2, true , "bvc"},
  OpInfo{OpType::Eor, OpMode::IndirectY, 5, true , "eor"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Nop, OpMode::ZeroPageX, 4, false, "nop"},
  OpInfo{OpType::Eor, OpMode::ZeroPageX, 4, false, "eor"},
  OpInfo{OpType::Lsr, OpMode::ZeroPageX, 6, false, "lsr"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Cli, OpMode::Implied  , 2, false, "cli"},
  OpInfo{OpType::Eor, OpMode::AbsoluteY, 4, true , "eor"},
  OpInfo{OpType::Nop, OpMode::Implied  , 2, false, "nop"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Nop, OpMode::AbsoluteX, 4, true , "nop"},
  OpInfo{OpType::Eor, OpMode::AbsoluteX, 4, true , "eor"},
  OpInfo{OpType::Lsr, OpMode::AbsoluteX, 7, false, "lsr"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Rts, OpMode::Implied  , 6, false, "rts"},
  OpInfo{OpType::Adc, OpMode::IndirectX, 6, false, "adc"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Nop, OpMode::ZeroPage , 3, false, "nop"},
  OpInfo{OpType::Adc, OpMode::ZeroPage , 3, false, "adc"},
  OpInfo{OpType::Ror, OpMode::ZeroPage , 5, false, "ror"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Pla, OpMode::Implied  , 4, false, "pla"},
  OpInfo{OpType::Adc, OpMode::Immediate, 2, false, "adc"},
  OpInfo{OpType::Ror, OpMode::Implied  , 2, false, "ror"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Jmp, OpMode::Indirect , 5, false, "jmp"},
  OpInfo{OpType::Adc, OpMode::Absolute , 4, false, "adc"},
  OpInfo{OpType::Ror, OpMode::Absolute , 6, false, "ror"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Bvs, OpMode::Relative , 2, true , "bvs"},
  OpInfo{OpType::Adc, OpMode::IndirectY, 5, true , "adc"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Nop, OpMode::ZeroPageX, 4, false, "nop"},
  OpInfo{OpType::Adc, OpMode::ZeroPageX, 4, false, "adc"},
  OpInfo{OpType::Ror, OpMode::ZeroPageX, 6, false, "ror"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Sei, OpMode::Implied  , 2, false, "sei"},
  OpInfo{OpType::Adc, OpMode::AbsoluteY, 4, true , "adc"},
  OpInfo{OpType::Nop, OpMode::Implied  , 2, false, "nop"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Nop, OpMode::AbsoluteX, 4, true , "nop"},
  OpInfo{OpType::Adc, OpMode::AbsoluteX, 4, true , "adc"},
  OpInfo{OpType::Ror, OpMode::AbsoluteX, 7, false, "ror"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Nop, OpMode::Immediate, 2, false, "nop"},
  OpInfo{OpType::Sta, OpMode::IndirectX, 6, false, "sta"},
  OpInfo{OpType::Nop, OpMode::Immediate, 2, false, "nop"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Sty, OpMode::ZeroPage , 3, false, "sty"},
  OpInfo{OpType::Sta, OpMode::ZeroPage , 3, false, "sta"},
  OpInfo{OpType::Stx, OpMode::ZeroPage , 3, false, "stx"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Dey, OpMode::Implied  , 2, false, "dey"},
  OpInfo{OpType::Nop, OpMode::Immediate, 2, false, "nop"},
  OpInfo{OpType::Txa, OpMode::Implied  , 2, false, "txa"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Sty, OpMode::Absolute , 4, false, "sty"},
  OpInfo{OpType::Sta, OpMode::Absolute , 4, false, "sta"},
  OpInfo{OpType::Stx, OpMode::Absolute , 4, false, "stx"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Bcc, OpMode::Relative , 2, true , "bcc"},
  OpInfo{OpType::Sta, OpMode::IndirectY, 6, false, "sta"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Sty, OpMode::ZeroPageX, 4, false, "sty"},
  OpInfo{OpType::Sta, OpMode::ZeroPageX, 4, false, "sta"},
  OpInfo{OpType::Stx, OpMode::ZeroPageY, 4, false, "stx"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Tya, OpMode::Implied  , 2, false, "tya"},
  OpInfo{OpType::Sta, OpMode::AbsoluteY, 5, false, "sta"},
  OpInfo{OpType::Txs, OpMode::Implied  , 2, false, "txs"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Sta, OpMode::AbsoluteX, 5, false, "sta"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Ldy, OpMode::Immediate, 2, false, "ldy"},
  OpInfo{OpType::Lda, OpMode::IndirectX, 6, false, "lda"},
  OpInfo{OpType::Ldx, OpMode::Immediate, 2, false, "ldx"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Ldy, OpMode::ZeroPage , 3, false, "ldy"},
  OpInfo{OpType::Lda, OpMode::ZeroPage , 3, false, "lda"},
  OpInfo{OpType::Ldx, OpMode::ZeroPage , 3, false, "ldx"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Tay, OpMode::Implied  , 2, false, "tay"},
  OpInfo{OpType::Lda, OpMode::Immediate, 2, false, "lda"},
  OpInfo{OpType::Tax, OpMode::Implied  , 2, false, "tax"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Ldy, OpMode::Absolute , 4, false, "ldy"},
  OpInfo{OpType::Lda, OpMode::Absolute , 4, false, "lda"},
  OpInfo{OpType::Ldx, OpMode::Absolute , 4, false, "ldx"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Bcs, OpMode::Relative , 2, true , "bcs"},
  OpInfo{OpType::Lda, OpMode::IndirectY, 5, true , "lda"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Ldy, OpMode::ZeroPageX, 4, false, "ldy"},
  OpInfo{OpType::Lda, OpMode::ZeroPageX, 4, false, "lda"},
  OpInfo{OpType::Ldx, OpMode::ZeroPageY, 4, false, "ldx"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Clv, OpMode::Implied  , 2, false, "clv"},
  OpInfo{OpType::Lda, OpMode::AbsoluteY, 4, true , "lda"},
  OpInfo{OpType::Tsx, OpMode::Implied  , 2, false, "tsx"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Ldy, OpMode::AbsoluteX, 4, true , "ldy"},
  OpInfo{OpType::Lda, OpMode::AbsoluteX, 4, true , "lda"},
  OpInfo{OpType::Ldx, OpMode::AbsoluteY, 4, true , "ldx"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Cpy, OpMode::Immediate, 2, false, "cpy"},
  OpInfo{OpType::Cmp, OpMode::IndirectX, 6, false, "cmp"},
  OpInfo{OpType::Nop, OpMode::Immediate, 2, false, "nop"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Cpy, OpMode::ZeroPage , 3, false, "cpy"},
  OpInfo{OpType::Cmp, OpMode::ZeroPage , 3, false, "cmp"},
  OpInfo{OpType::Dec, OpMode::ZeroPage , 5, false, "dec"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Iny, OpMode::Implied  , 2, false, "iny"},
  OpInfo{OpType::Cmp, OpMode::Immediate, 2, false, "cmp"},
  OpInfo{OpType::Dex, OpMode::Implied  , 2, false, "dex"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Cpy, OpMode::Absolute , 4, false, "cpy"},
  OpInfo{OpType::Cmp, OpMode::Absolute , 4, false, "cmp"},
  OpInfo{OpType::Dec, OpMode::Absolute , 6, false, "dec"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Bne, OpMode::Relative , 2, true , "bne"},
  OpInfo{OpType::Cmp, OpMode::IndirectY, 5, true , "cmp"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Nop, OpMode::ZeroPageX, 4, false, "nop"},
  OpInfo{OpType::Cmp, OpMode::ZeroPageX, 4, false, "cmp"},
  OpInfo{OpType::Dec, OpMode::ZeroPageX, 6, false, "dec"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Cld, OpMode::Implied  , 2, false, "cld"},
  OpInfo{OpType::Cmp, OpMode::AbsoluteY, 4, true , "cmp"},
  OpInfo{OpType::Nop, OpMode::Implied  , 2, false, "nop"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Nop, OpMode::AbsoluteX, 4, true , "nop"},
  OpInfo{OpType::Cmp, OpMode::AbsoluteX, 4, true , "cmp"},
  OpInfo{OpType::Dec, OpMode::AbsoluteX, 7, false, "dec"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Cpx, OpMode::Immediate, 2, false, "cpx"},
  OpInfo{OpType::Sbc, OpMode::IndirectX, 6, false, "sbc"},
  OpInfo{OpType::Nop, OpMode::Immediate, 2, false, "nop"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Cpx, OpMode::ZeroPage , 3, false, "cpx"},
  OpInfo{OpType::Sbc, OpMode::ZeroPage , 3, false, "sbc"},
  OpInfo{OpType::Inc, OpMode::ZeroPage , 5, false, "inc"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Inx, OpMode::Implied  , 2, false, "inx"},
  OpInfo{OpType::Sbc, OpMode::Immediate, 2, false, "sbc"},
  OpInfo{OpType::Nop, OpMode::Implied  , 2, false, "nop"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Cpx, OpMode::Absolute , 4, false, "cpx"},
  OpInfo{OpType::Sbc, OpMode::Absolute , 4, false, "sbc"},
  OpInfo{OpType::Inc, OpMode::Absolute , 6, false, "inc"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Beq, OpMode::Relative , 2, true , "beq"},
  OpInfo{OpType::Sbc, OpMode::IndirectY, 5, true , "sbc"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Nop, OpMode::ZeroPageX, 4, false, "nop"},
  OpInfo{OpType::Sbc, OpMode::ZeroPageX, 4, false, "sbc"},
  OpInfo{OpType::Inc, OpMode::ZeroPageX, 6, false, "inc"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Sed, OpMode::Implied  , 2, false, "sed"},
  OpInfo{OpType::Sbc, OpMode::AbsoluteY, 4, true , "sbc"},
  OpInfo{OpType::Nop, OpMode::Implied  , 2, false, "nop"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
  OpInfo{OpType::Nop, OpMode::AbsoluteX, 4, true , "nop"},
  OpInfo{OpType::Sbc, OpMode::AbsoluteX, 4, true , "sbc"},
  OpInfo{OpType::Inc, OpMode::AbsoluteX, 7, false, "inc"},
  OpInfo{OpType::Ill, OpMode::Implied  , 0, false, "ill"},
};
// clang-format on

}  // namespace nes
